if(EXISTS "/home/karthik/IITB/MTP/tchecker/test/unit-tests/unittest_tests-b858cb2.cmake")
  include("/home/karthik/IITB/MTP/tchecker/test/unit-tests/unittest_tests-b858cb2.cmake")
else()
  add_test(unittest_NOT_BUILT-b858cb2 unittest_NOT_BUILT-b858cb2)
endif()
